<a href="https://colab.research.google.com/github/007khun159/Data_En_libary-/blob/main/Data_libary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
array1 = np.array(range(2,6))
print(array1)
array2 = np.array([[1,3],[4,6]])
print(array2)

[2 3 4 5]
[[1 3]
 [4 6]]


In [ ]:
#Example random.rand

data = np.random.rand(2,4)
print(data)

[[0.15759923 0.49454254 0.72208911 0.56650815]
 [0.62524607 0.90661483 0.82888073 0.76675429]]


In [ ]:

#Example by Unifrom 

data = np.random.uniform(1,10,(2,4))
print(data)

[[6.82339733 5.24174103 7.24991631 8.25996717]
 [6.44052811 7.83551216 2.87425028 7.77178313]]


In [ ]:
#Example1 method array


data = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(data)

[[2 4 6]
 [3 5 7]
 [8 6 4]]


In [ ]:
#Example2 method array


d_array = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(type(data))
print('List of d_array')
print(d_array)


data = np.array(d_array)
print(type(data))
print('data is')
print(data)


<class 'numpy.ndarray'>
List of d_array
[[2 4 6]
 [3 5 7]
 [8 6 4]]
<class 'numpy.ndarray'>
data is
[[2 4 6]
 [3 5 7]
 [8 6 4]]


In [ ]:
#Method arange


data_array = np.arange(10)
print(data_array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Method linspace 
d_array = np.linspace(1,9,6)
print(d_array)

[1.  2.6 4.2 5.8 7.4 9. ]


In [ ]:
#Method  Zeros
data_array_zeros = np.zeros((3,2),dtype = np.int32)
print(data_array_zeros)

[[0 0]
 [0 0]
 [0 0]]


In [ ]:
#Method ones 


data_array_ones = np.ones((3,2),dtype = np.float32)
print(data_array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Method identity  / eye


i_matrix = np.identity(3,dtype=np.int64)
print(i_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
i_matrix = np.eye(3,dtype=np.int64)
print(i_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
i_matrix = np.eye(3,4,dtype=np.int64)
print(i_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [ ]:
#Method size(example)

d_array = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(d_array)
d_array.size

[[2 4 6]
 [3 5 7]
 [8 6 4]]


9

In [ ]:
data_array = np.arange(10)
print(data_array)
data_array.size

[0 1 2 3 4 5 6 7 8 9]


10

In [ ]:
#Method shape (example)

d_array1 = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(d_array1)
d_array.shape

[[2 4 6]
 [3 5 7]
 [8 6 4]]


(3, 3)

In [ ]:
d_array2 = np.array([1,2,3])
print(d_array2)
d_array2.shape

[1 2 3]


(3,)

In [ ]:
#Method ndim  (example)

d_array1 = np.array([[2,4,6],[3,5,7],[8,6,4]])
print(d_array1)
d_array1.ndim

[[2 4 6]
 [3 5 7]
 [8 6 4]]


2

In [ ]:
d_array2 = np.array([1,2,3])
print(d_array2)
d_array2.ndim

[1 2 3]


1

In [ ]:
#method  astype(example)

num_string = np.array(['5.76','-17.6','85'],dtype = np.string_)
num = num_string.astype(float)
print(num)
int_num = num.astype(np.int32)
print(int_num)

[  5.76 -17.6   85.  ]
[  5 -17  85]


In [ ]:
#method reshape(example)
#เปลี่ยนรูปร่าง
array1 = np.arange(12)
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
array2 = array1.reshape(3,4)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
array3 = array2.reshape(4,3)
print(array3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
#Method reshape(example cont. in ravel())

#ย้อนกลับ
array2 = array1.reshape(3,4)
print(array2)
print(array2.ravel())



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
array3 = array2.reshape(4,3)
print(array3)
print(array3.ravel())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# Slide after 41

In [ ]:
#อ้างอิงต่ำแหน่งของข้อมูล


array = np.array([[3,5,7],[4,8,16]])
print("row 0 column 0 is",array[0][0])
print('row 1 column 2 is',array[1][2])

row 0 column 0 is 3
row 1 column 2 is 16


In [ ]:
array = np.array([[3,5,7],[4,8,16]])
print('all elements in row1',array[1][:])
print('all elements in row1',array[:][1])

#another style

print('all elements in row1',array[1,:])
print('all elments in column1 ',array [:,1])




all elements in row1 [ 4  8 16]
all elements in row1 [ 4  8 16]
all elements in row1 [ 4  8 16]
all elments in column1  [5 8]


In [ ]:
#Indexing and slicing 1 

arr = np.array([[1,2,3],[4,5,6]])
c_array = arr.copy()
print(arr)
print(c_array)
print(c_array[1:])
arr[1:] =99
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]]
[[ 1  2  3]
 [99 99 99]]


In [ ]:
#Indexing and slicing 2
arr_2d = np.arange(12).reshape(3,4)
print(arr_2d)
print(arr_2d[:2,1:])
print()
arr_2d_copy = arr_2d.copy()
print(arr_2d_copy)
print()
arr_2d_copy[1:,:]= 5
print(arr_2d_copy)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[1 2 3]
 [5 6 7]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[0 1 2 3]
 [5 5 5 5]
 [5 5 5 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#Boolean indexing 

data = np.random.randn(6,3)
print(data)
data[data<0]  =0 
print(data)

[[-0.65571725  0.42538206  0.97061939]
 [-0.86918444  2.14620015  0.26074717]
 [ 0.23627126  2.01500324  0.10114325]
 [ 1.01608268 -0.64752244 -1.20438919]
 [-0.82643117 -0.17708849  0.32088918]
 [ 0.95088817 -0.91163606  1.30915272]]
[[0.         0.42538206 0.97061939]
 [0.         2.14620015 0.26074717]
 [0.23627126 2.01500324 0.10114325]
 [1.01608268 0.         0.        ]
 [0.         0.         0.32088918]
 [0.95088817 0.         1.30915272]]


In [ ]:
arr = np.arange(1,11)
arr2 = arr>7
print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False False False  True  True  True]


In [ ]:
names  = np.array(['Tom','Eddy','Mary','Tom','Bill','Tom','Eddy'])
names == 'Eddy'


array([False,  True, False, False, False, False,  True])

In [ ]:
#Error เกิดจากจำนวนของ Metrix ที่ไม่เท่ากันของ names
names  = np.array(['Tom','Eddy','Mary','Tom','Bill','Eddy'])
data = np.random.randn(6,4)
print(names)
print(data,'\n')
print(data[names == 'Eddy'])

['Tom' 'Eddy' 'Mary' 'Tom' 'Bill' 'Eddy']
[[ 0.0427405  -0.71666834  0.39939026  0.43751102]
 [-1.04302954 -0.34423027 -0.79737487  0.94498148]
 [ 0.04102763 -0.27624524 -0.7854206   1.20611357]
 [-0.62031353  0.25390687  0.18225921  0.26858202]
 [ 1.09420307 -1.13561796  0.73554237  0.2393857 ]
 [-0.25043578  0.88128922 -0.4704835   1.22417754]] 

[[-1.04302954 -0.34423027 -0.79737487  0.94498148]
 [-0.25043578  0.88128922 -0.4704835   1.22417754]]


In [ ]:
#Matrix caculate

arr  = np.empty((6,4))
for i in range(6):
  arr[i]=i
print(arr)
print(arr[[3,2,5]])
arr1 = np.arange(24).reshape(6,4)
print(arr1)
print(arr1[[3,2,5],[2,0,1]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]]
[[3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [5. 5. 5. 5.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[14  8 21]


In [ ]:
#Unary Universal Function


array1 = np.array([2.2,3.4,4.6])
print(array1)
print(np.ceil(array1))
print(np.floor(array1))
print(np.exp(array1))
print(np.sqrt(array1))

[2.2 3.4 4.6]
[3. 4. 5.]
[2. 3. 4.]
[ 9.0250135  29.96410005 99.48431564]
[1.4832397  1.84390889 2.14476106]


In [ ]:
array1 = np.arange(2,6)
array2 = np.arange(1,5)
print(array1,array2)
print(np.add(array1,array2))
print(np.subtract(array1,array2))
print(np.multiply(array1,array2))
print(np.power(array1,array2))
print(np.maximum(array1,array2))
print(np.mod(array1,array2))

[2 3 4 5] [1 2 3 4]
[3 5 7 9]
[1 1 1 1]
[ 2  6 12 20]
[  2   9  64 625]
[2 3 4 5]
[0 1 1 1]


In [ ]:
#Bassic array Statisticla Methods
array = np.random.randn(3,4)
print(array)
print('mean =',array.mean())
print(np.mean(array))
print('sum =',array.sum())
print('std =',array.std())

[[-0.86179128  2.14788996 -0.25830957 -0.43150677]
 [ 0.93078353  0.02455854  0.99120536 -0.28926786]
 [-1.81897937  0.8038274   0.701592    1.14735954]]
mean = 0.257280122348535
0.257280122348535
sum = 3.0873614681824195
std = 1.021083387469205


In [ ]:
arry = np.array([[1,2],[3,4],[5,6]])
print("array =",arry)
print('cumsum :',arry.cumsum())
print('cumsum axis =1 :')
print(arry.cumsum(axis=1))
print(arry.cumprod(axis=0))

array = [[1 2]
 [3 4]
 [5 6]]
cumsum : [ 1  3  6 10 15 21]
cumsum axis =1 :
[[ 1  3]
 [ 3  7]
 [ 5 11]]
[[ 1  2]
 [ 3  8]
 [15 48]]


In [ ]:
scores  =[53 ,#score1
          43,#score2
          39,#score3
          93,#score4
          28] #score5

bmi = [150,50,22.2] #height , weight,BMI